name: Code Checks and Tests

on: [ push, pull_request]

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      go-path: ${{ steps.setup-go.outputs.go-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'


  code_check:
    name: run code quality checks
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run go vet
        run: go vet $(go list ./...)

  test:
    name: run tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run go test
        run: go test -v ./...


