name: Code Checks and Tests

on: [ push, pull_request]

jobs:
  code_check:
    name: run code quality checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install golint
        run: |
          go get -u golang.org/x/lint/golint@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run go vet
        run: go vet $(go list ./...)

      - name: Run golint
        run: golang.org/x/lint/golint -set_exit_status $(go list ./...)


